name: Docker
on:
	push:
		branches:
			- master
		tags:
			- v*

jobs:
	build:
		name: Build and Tag Docker Image
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@master
		- name: Build, Tag, Publish Docker
			uses: HurricanKai/Publish-Docker-Github-Action@1.12.1
			with:
				name: bspaulding/slowcart
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
				tagging: true
